### ISSUE TITLE
alternative way of concatenating two LSTM cell

### ISSUE THREAD

**Issue by saria85** [sbillburg/CRNN-with-STN#10]
Hello again:)

I am working on your code and almost done. except I need to change one line of the code:
`rnn2_merged = concatenate([rnn_2, rnn_2b])` in which you are concatenating them.
Can you please help me with this. I want to keep the same structure but without Concatenate?
to put it another way, what will be the alternative way of concatenating them in `keras` but without using concatenate?

Thanks for taking the time.

**Comment by sbillburg** [comment]
Keras is tensorflow-based, so you can use functions from tensorflow to concatenate two tensors together.

**Comment by saria85** [comment]
Could you please share a link with me in which doing this?
I just want to make sure my revised code will be exactly the same as code here.

Thanks in advance:)

**Comment by sbillburg** [comment]
> Could you please share a link with me in which doing this?
> I just want to make sure my revised code will be exactly the same as code here.
> 
> Thanks in advance:)

https://apimirror.com/tensorflow~python/tf/concat

Or you can look for concatenate function in Keras source code, as a reference.

**Comment by saria85** [comment]
It did not help actually, Im trying to convert your code to CoreMl, but CoreMl does not support concatenate!
this guy changed his code https://github.com/iwantooxxoox/Keras-OpenFace/issues/1 to change the channel to be able to do so.
Can you please have a look to see if it is doable on your code?

**Comment by saria85** [comment]
Can you please let me know about this?
here `rnn2_merged = concatenate([rnn_2, rnn_2b])`
the dimension of` rnn_2 = (?, ?, 128)`
and ` rnn_2b= (?, ?, 128)`
is there anyway we can give the actual size to rnn_2 and rnn_rb rather than `? `

Thanks again.

**Comment by sbillburg** [comment]
> Can you please let me know about this?
> here `rnn2_merged = concatenate([rnn_2, rnn_2b])`
> the dimension of` rnn_2 = (?, ?, 128)`
> and ` rnn_2b= (?, ?, 128)`
> is there anyway we can give the actual size to rnn_2 and rnn_rb rather than `? `
> Or because the lenght is varient it is not possible?
> 
> Thanks again.

You cannot set the specific dimension of rnn_2, two "? " depend on input dataset at the very beginning,  First'?' presents the batch size, and the second is 1/8 of input image width.
