### ISSUE TITLE
你好，加载模型时遇到了一些问题

### ISSUE THREAD

**Issue by wangwyForNewTime** [sbillburg/CRNN-with-STN#17]
当我修改config.py的模型路径load_model_path = '/home/user/WWY/CRNN-with-STN-master/weights_with_STN.hdf5' 
命令行报错：
ValueError: Layer #10 (named "spatial_transformer_1" in the current model) was found to correspond to layer spatial_transformer_1 in the save file. However the new layer spatial_transformer_1 expects 16 weights, but the saved weights have 8 elements.

如果是load_model_path = '/home/user/WWY/CRNN-with-STN-master/weights_without_STN.hdf5' 
命令行报错：
ValueError: axes don't match array

这两个错误在我以前没有遇到过，我不知道如何修改，麻烦作者解答一下困惑，谢谢啦

**Comment by wangwyForNewTime** [comment]
我解决了

**Comment by Naosekpam** [comment]
@wangwyForNewTime  Will you please let me know how the issue was solved? I am also facing the sam issue after downloading the pre-trained model.
