### ISSUE TITLE
input and output name

### ISSUE THREAD

**Issue by saria85** [sbillburg/CRNN-with-STN#8]
Again thanks for sharing your code with us.
I'd love working on your code and I want to use in my phone.
So I need to convet the keras model to core ML.
this is the function I need to call:
```

def convert(model,
            mode=None,
            image_input_names=[],
            preprocessing_args={},
            image_output_names=[],
            deprocessing_args={},
            class_labels=None,
            predicted_feature_name='classLabel',
            add_custom_layers = False,
            custom_conversion_functions = {})
```
I was wondering can you help me with the argument according to your code?
like what will be image_input_names,....

Thanks in advance for taking the time:)

**Comment by sbillburg** [comment]
https://github.com/sbillburg/CRNN-with-STN/blob/26e3d39467deb5756f7a718a2bb7e9ed904fc36f/Batch_Generator.py#L30

I guess you need "img_path"

**Comment by saria85** [comment]
Thanks for answering back:)
Is it `image_input_names`? 
what about other argument like `image_output_names`.
Also I got 20% accuracy after training your model, what can be wrong here?

Thanks
Saria

**Comment by sbillburg** [comment]
> Thanks for answering back:)
> Is it `image_input_names`?
> what about other argument like `image_output_names`.
> 
> Thanks
> Saria

As for my network, the output is a prediction word, there is no image output.
